spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/omc?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create