spring:
  datasource:
    url: jdbc:mysql://${testDbIp:127.0.0.1}:3306/omc_test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${testDbId:root}
    password: ${testDbPw:1111}
  jpa:
    hibernate:
      ddl-auto: create
